### ISSUE TITLE
Auth0 Issue

### ISSUE THREAD

**Issue by seanwu20** [connect-our-kids/impact-dashboard#32]
Recreate
* Login
* Going to terms and conditions, and then press back
* Login button does not say logout. Says login.
* Login button does not work. 
* Suspected issue: Auth0 cookies

**Comment by desiquinn** [comment]
This also happens on refresh
* login
* click refresh
* Logout button turns to login, sub menu disappears, and then login no longer works.

**Comment by seanwu20** [comment]
Issues is with loginWithRedirect getting called before it has a chance to finish
